# Файл docker-compose должен начинаться с тега версии.
#version: '3.9'
services:
  ubuntu-seminars:
    container_name: tg_sup_bot # имя контейнера
    platform: linux/amd64
    image: tg_sup_bot # название образа
    ports: # какие порты необходимо прокинуть, будут доступны localhost:port
      - 8080:8080
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=supp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=roma
    ports:
      - "6543:5432"

